#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

# Install Composer dependencies if vendor directory doesn't exist
if [ ! -d /var/www/html/vendor ]; then
    composer install --no-interaction --prefer-dist
fi

# Install Node dependencies if node_modules directory doesn't exist
if [ ! -d /var/www/html/node_modules ]; then
    npm ci
fi

# Run npm watch in background
npm run watch &

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
